name: Feature Request
description: File a feature request
title: "[Feature]: "
labels: ["feature", "triage"]
assignees:
  - octocat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: feature-desc
    attributes:
      label: Describe the feature you would like to see on the next version of our visual.
      description: Also tell us, how you or your organization/company can take part in financing this development?
      placeholder: Explain your needs with details!
      value: "That would be neat to have this awesome feature!"
    validations:
      required: true
  - type: dropdown
    id: customviz
    attributes:
      label: Custom Visual
      description: Which of our visual would you like to see this feature added on?
      options:
        - Preselected Slicer
        - Mass Filter
        - Data Refresher
    validations:
      required: true
  - type: checkboxes
    id: financial-support
    attributes:
      label: Would you or your company be ready in financing this feature?
      description: We might contact you in order to fix the terms of an enventual cooperation.
      options:
        - label: Yes, we can support this development!
          required: false
